version: "3.8"
services:
    nodejs:
        build:
            context: .
        image: asopf
        container_name: asopf-app
        restart: unless-stopped
        volumes:
            - ./:/app
        networks:
            - asopf

    db:
        image: mysql:8.0.21
        container_name: asopf-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - asopf

    nginx:
        image: nginx:1.19.2
        container_name: asopf-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/app
            - ./nginx-conf:/etc/nginx/conf.d
        depends_on:
            - nodejs
        networks:
            - asopf
volumes: 
    mysql:
networks:
    asopf: