version: "3.8"

services:
    asopf:
        build:
            context: .
        command: nodemon app.js
        expose:
            - "80"
        ports:
            - 8080:8080
        environment:
            # SERVER_PORT=8080
            # DATABASE_CONECTIONSTRING=mongodb://mongo:27017/notes
        volumes:
            - ./:/app
        command: npm run dev

    mysql:
        image: mysql:8.0.21
        ports:
            - 3306
        volumes:
            - mysql:/var/lib/mysql

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        links:
            - asopf
        ports:
            - "80:80"
        volumes:
            - ./etc/nginx/conf.d/server.conf:/etc/nginx/conf.d/server.conf
        
volumes:
    mysql: